version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
  build:
    commands:
      - echo Build started on `date`
      - echo Installing dependencies...
      - pip install -r requirements.txt
      - echo Running tests...
      - pytest
      - echo Building the Docker image...
      - docker build -t my-flask-app .
      - echo Pushing the Docker image to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
      - docker tag my-flask-app:latest $ECR_REGISTRY/my-flask-app:latest
      - docker push $ECR_REGISTRY/my-flask-app:latest
      - echo Build completed on `date`
