version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.10
    commands:
      - apt-get update
      - apt-get install -y docker.io
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
  build:
    commands:
      - echo Building Docker image...
      - docker build -t $ECR_REPOSITORY_NAME:$CODEBUILD_RESOLVED_SOURCE_VERSION .
      - docker tag $ECR_REPOSITORY_NAME:$CODEBUILD_RESOLVED_SOURCE_VERSION $ECR_REPOSITORY_NAME:latest
      - echo Pushing Docker images...
      - docker push $ECR_REPOSITORY_NAME:$CODEBUILD_RESOLVED_SOURCE_VERSION
      - docker push $ECR_REPOSITORY_NAME:latest
  post_build:
    commands:
      - echo Build completed on `date`
      
artifacts:
  files:
    - '**/*'
